Create issues/PRs tagging system
BobuxBot/BobuxAdmin pull request #21
Opened 2023-03-07 20:33 UTC by Exenifix

Closes #20

2023-03-08 21:06 UTC, Pandabweer requested changes
I didn't test this code. I don't want to setup the whole environment right now. I did do some pointers, I hope Skev will do testing.

2023-03-08 21:06 UTC, enriquebos commented on ext/github.py
> +        print(ordered)
Is this print mandatory inside the main?

2023-03-08 21:06 UTC, enriquebos commented on ext/github.py
> +            items = list(filter(lambda x: x is not None, await asyncio.gather(*coros)))
```suggestion
            items = list(filter(None, await asyncio.gather(*coros)))
``` 
This is exactly the same and easier on the eyes.

2023-03-08 21:06 UTC, enriquebos commented on ext/github.py
> +    async def on_message(self, msg: disnake.Message):
Ignoring bots?

2023-03-08 21:06 UTC, Pandabweer commented on utils/github.py
> +        try:
Better to remove the code that won't raise a `ClientResponseError`. Yes it's obvious but if done on other error it could be harder to read.

2023-03-08 21:10 UTC, Exenifix commented on ext/github.py
> +    async def on_message(self, msg: disnake.Message):
There is developer role ID check, none of bots are supposed to have the role

2023-03-08 21:20 UTC, Pandabweer approved these changes

2023-03-09 01:32 UTC, iamSkev approved these changes

2023-03-09 01:32 UTC, merged